name: CloudMart CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build User Service
        run: |
          docker build \
          -t cloudmart-user \
          ./services/user-service

      - name: Build Product Service
        run: |
          docker build \
          -t cloudmart-product \
          ./services/product-service

      - name: Build Order Service
        run: |
          docker build \
          -t cloudmart-order \
          ./services/order-service

      - name: Docker Compose Validation
        run: |
          docker compose config

      - name: Start Stack
        run: |
          docker compose up -d --build

      - name: Wait For Services
        run: sleep 20

      - name: Test User Service
        run: |
          curl --fail http://localhost:8000/users

      - name: Test Product Service
        run: |
          curl --fail http://localhost:8001/products

      - name: Test Order Service
        run: |
          curl --fail http://localhost:8002/orders

      - name: Test Order Service
        run: |
          curl -X POST http://localhost:8002/orders \
            -H "Content-Type: application/json" \
            -d '{"user":"rohit","product":"laptop"}'
      - name: Docker logs
        run: |
          docker compose logs --tail=20 notification-service

      - name: Stop Stack
        if: always()
        run: |
          docker compose down
